---
- name: Copy config files
  copy: src={{item}} dest=$HOME/.{{item}}
  with_items:
    - tmux.conf
    - editrc
    - git-completion
    - myzshrc
    - aliasrc
    - gitconfig

- name: Use vagrant without passwords
  become: yes
  command: sudo gpasswd -a ${USER} libvirt

- name: Detect ohmyzsh
  stat: path=$HOME/.oh-my-zsh
  register: ohmyzsh_installed

- name: Cloning oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  when: ohmyzsh_installed.stat.exists == False

- name: Creating new ~/.zshrc
  copy: src=~/.oh-my-zsh/templates/zshrc.zsh-template dest=~/.zshrc

- name: Load myzshrc
  lineinfile: path=$HOME/.zshrc regexp='^source ~/.myzshrc' line='source ~/.myzshrc'

- name: Remove ohmyzshrc theme
  lineinfile: path=$HOME/.zshrc regexp='^ZSH_THEME="(robbyrussell)"' line='ZSH_THEME="avit"'

- name: Set ohmyzshrc theme
  lineinfile: path=$HOME/.zshrc regexp='^ZSH_THEME\=\"avit\"' line='ZSH_THEME="avit"'

- name: Change default shell to zsh
  become: yes
  user: name=jonathan shell=/usr/bin/zsh

- name: Detect dein installation
  stat: path=~/.config/nvim/dein
  register: dein_installed

- name: Setup dein - nvim plugin manager
  shell: curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh | sh -s ~/.config/nvim/dein 
  when: dein_installed.stat.exists == False

- name: Copy neovim config
  copy: src=neovim.init dest=$HOME/.config/nvim/init.vim

- name: Create .font directory
  file: path=~/.fonts state=directory mode=0755

- name: Install neovim font
  copy: src=sauce_code_pro_nerd_font.ttf dest=$HOME/.fonts/sauce_code_pro_nerd_font.ttf

- name: Set terminal colorscheme to Solarized Dark
  dconf: key={{item.key}} value="'{{item.value}}'" state=present
  with_items:
    - { 'key': '/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color', 'value': 'rgb(131,148,150)' }
    - { 'key': '/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color', 'value': 'rgb(0,43,54)' }

- name: Remove system theme colors
  dconf: key='/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors' value='false' state=present

- name: Remap capslock to ctrl
  dconf: key=/org/gnome/desktop/input-sources/xkb-options value="['caps:ctrl_modifier']" state=present

- name: Set terminal font
  dconf: key=/org/gnome/desktop/interface/monospace-font-name value="'SauceCodePro Nerd Font 16'" state=present

- name: Set gnome terminal to run custom command on startup 
  dconf: key=/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-custom-command value=true state=present

- name: Set gnome terminal to invoke zsh as default shell for gnome terminal
  dconf: key=/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/custom-command value="'zsh'" state=present

- name: Install python3 neovim
  become: yes
  command: pip3 install neovim

- name: Create dev directory
  file: path=$HOME/dev state=directory mode=0755

- name: Create go directory
  file: path=$HOME/dev/go state=directory mode=0755

- name: Create go directories
  file: path=$HOME/dev/go/{{item}} state=directory mode=0755
  with_items:
    - src
    - bin
    - pkg

