---
- name: Install packages
  become: yes
  dnf:
          name: ['the_silver_searcher', 'git', 'zsh', 'neovim', 'gnome-tweak-tool', 'libselinux-python', 'golang', 'direnv', 'vagrant', 'docker', 'python2-psutil', 'vagrant-libvirt']
          state: present
    
